import type { AirportOption } from "@/lib/travel/types";

export const europeAirports: AirportOption[] = [
  {
    id: "airport-zrh",
    iataCode: "ZRH",
    name: "Zurich Airport",
    cityName: "Zurich",
    countryName: "Switzerland",
    latitude: 47.4581,
    longitude: 8.5555,
    type: "airport",
  },
  {
    id: "airport-gva",
    iataCode: "GVA",
    name: "Geneva Airport",
    cityName: "Geneva",
    countryName: "Switzerland",
    latitude: 46.2381,
    longitude: 6.1089,
    type: "airport",
  },
  {
    id: "airport-bsl",
    iataCode: "BSL",
    name: "EuroAirport Basel Mulhouse Freiburg",
    cityName: "Basel",
    countryName: "Switzerland",
    latitude: 47.5989,
    longitude: 7.5292,
    type: "airport",
  },
  {
    id: "airport-ams",
    iataCode: "AMS",
    name: "Amsterdam Airport Schiphol",
    cityName: "Amsterdam",
    countryName: "Netherlands",
    latitude: 52.3105,
    longitude: 4.7683,
    type: "airport",
  },
  {
    id: "airport-bcn",
    iataCode: "BCN",
    name: "Barcelona El Prat Airport",
    cityName: "Barcelona",
    countryName: "Spain",
    latitude: 41.2974,
    longitude: 2.0833,
    type: "airport",
  },
  {
    id: "airport-ber",
    iataCode: "BER",
    name: "Berlin Brandenburg Airport",
    cityName: "Berlin",
    countryName: "Germany",
    latitude: 52.3667,
    longitude: 13.5033,
    type: "airport",
  },
  {
    id: "airport-cdg",
    iataCode: "CDG",
    name: "Paris Charles de Gaulle Airport",
    cityName: "Paris",
    countryName: "France",
    latitude: 49.0097,
    longitude: 2.5479,
    type: "airport",
  },
  {
    id: "airport-cph",
    iataCode: "CPH",
    name: "Copenhagen Airport",
    cityName: "Copenhagen",
    countryName: "Denmark",
    latitude: 55.618,
    longitude: 12.656,
    type: "airport",
  },
  {
    id: "airport-fco",
    iataCode: "FCO",
    name: "Rome Fiumicino Airport",
    cityName: "Rome",
    countryName: "Italy",
    latitude: 41.8003,
    longitude: 12.2389,
    type: "airport",
  },
  {
    id: "airport-lis",
    iataCode: "LIS",
    name: "Lisbon Airport",
    cityName: "Lisbon",
    countryName: "Portugal",
    latitude: 38.7742,
    longitude: -9.1342,
    type: "airport",
  },
  {
    id: "airport-prg",
    iataCode: "PRG",
    name: "Vaclav Havel Airport Prague",
    cityName: "Prague",
    countryName: "Czechia",
    latitude: 50.1008,
    longitude: 14.26,
    type: "airport",
  },
  {
    id: "airport-vie",
    iataCode: "VIE",
    name: "Vienna International Airport",
    cityName: "Vienna",
    countryName: "Austria",
    latitude: 48.1103,
    longitude: 16.5697,
    type: "airport",
  },
  {
    id: "airport-ath",
    iataCode: "ATH",
    name: "Athens International Airport",
    cityName: "Athens",
    countryName: "Greece",
    latitude: 37.9364,
    longitude: 23.9445,
    type: "airport",
  },
  {
    id: "airport-mxp",
    iataCode: "MXP",
    name: "Milan Malpensa Airport",
    cityName: "Milan",
    countryName: "Italy",
    latitude: 45.63,
    longitude: 8.723,
    type: "airport",
  },
];

export function findAirportByIata(iataCode: string) {
  return europeAirports.find((airport) => airport.iataCode === iataCode.toUpperCase());
}
